language: python
install:
  - pip install -r requirements.txt
  - pip install pytest python-coveralls pytest-cov
python:
  - "2.7"
  - "3.4"
script:
  - py.test test_pyfmt.py --cov pyfmt --cov-report term-missing
after_success:
  - coveralls
