language: python
install:
  - pip install -r requirements.txt
  - [ "$(git branch | grep "*" | sed 's/..//')" = "master" ] || pip install git+https://github.com/psycojoker/baron -U
  - pip install pytest python-coveralls pytest-cov
python:
  - "2.7"
script:
  - py.test test_pyfmt.py --cov pyfmt --cov-report term-missing
after_success:
  - coveralls
